name: Monitor CPU Utilization

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  monitor:
    runs-on: ubuntu22.04

    steps:
      - name: Monitor CPU Utilization
        run: ssh ubuntu@your-machine 'bash -s' < /scripts/monitor-cpu.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
